DROP TABLE IF EXISTS order_status_log; DROP TABLE IF EXISTS api_idempotency; DROP TABLE IF EXISTS reserve_order;
DROP TABLE IF EXISTS business_travel_car; DROP TABLE IF EXISTS business_hotel_room; DROP TABLE IF EXISTS business; DROP TABLE IF EXISTS wx_user;
CREATE TABLE wx_user(id BIGINT AUTO_INCREMENT PRIMARY KEY,openid VARCHAR(128) NOT NULL UNIQUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,last_seen_at TIMESTAMP);
CREATE TABLE business(id BIGINT PRIMARY KEY,name VARCHAR(128) NOT NULL,business_type VARCHAR(16) NOT NULL,status VARCHAR(16) NOT NULL,deleted_at TIMESTAMP);
CREATE TABLE business_travel_car(id BIGINT PRIMARY KEY,business_id BIGINT NOT NULL,model VARCHAR(128),seat_num INT,status VARCHAR(16),deleted_at TIMESTAMP);
CREATE TABLE business_hotel_room(id BIGINT PRIMARY KEY,business_id BIGINT NOT NULL,name VARCHAR(128),bed_spec VARCHAR(128),status VARCHAR(16),deleted_at TIMESTAMP);
CREATE TABLE reserve_order(id BIGINT AUTO_INCREMENT PRIMARY KEY,order_no VARCHAR(32) UNIQUE,openid VARCHAR(128),user_id BIGINT,business_id BIGINT,business_name_snapshot VARCHAR(128),business_type VARCHAR(16),service_type VARCHAR(16),contact_name VARCHAR(64),contact_phone VARCHAR(32),people_num INT,service_date DATE,status VARCHAR(16),car_id BIGINT,car_spec_snapshot VARCHAR(255),car_quantity INT,service_mode VARCHAR(16),room_id BIGINT,room_spec_snapshot VARCHAR(255),room_quantity INT,meal_period VARCHAR(16),option_snapshot_json VARCHAR(1000),extra_json VARCHAR(1000),confirmed_at TIMESTAMP,cancelled_at TIMESTAMP,cancel_source VARCHAR(16),cancel_reason VARCHAR(500),version INT DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE order_status_log(id BIGINT AUTO_INCREMENT PRIMARY KEY,order_id BIGINT,from_status VARCHAR(16),to_status VARCHAR(16),operator_type VARCHAR(16),operator_id BIGINT,reason VARCHAR(500),request_id VARCHAR(64),created_at TIMESTAMP);
CREATE TABLE api_idempotency(id BIGINT AUTO_INCREMENT PRIMARY KEY,openid VARCHAR(128),idempotency_key VARCHAR(128),request_hash CHAR(64),response_ref VARCHAR(128),status VARCHAR(16),expires_at TIMESTAMP,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(openid,idempotency_key));
