DROP TABLE IF EXISTS file_resource;
CREATE TABLE file_resource (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, storage_key VARCHAR(255) NOT NULL UNIQUE,
 public_url VARCHAR(1024) NOT NULL, original_name VARCHAR(255), mime_type VARCHAR(64) NOT NULL,
 size_bytes BIGINT NOT NULL, sha256 CHAR(64) NOT NULL, status VARCHAR(16) NOT NULL,
 created_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3), updated_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
 deleted_at TIMESTAMP(3)
);
