package com.mapvendor.module.order;
import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.mapvendor.MapVendorApplication;
import com.mapvendor.module.order.dto.AppOrderCreateRequest;
import com.mapvendor.module.order.domain.*;
import com.mapvendor.module.order.service.AppOrderCreateService;
import java.time.LocalDate; import java.util.concurrent.*; import java.util.*;
import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.context.jdbc.Sql; import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest(classes=MapVendorApplication.class,properties={"spring.datasource.url=jdbc:h2:mem:appcreate;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1","spring.datasource.username=sa","spring.datasource.password=","spring.flyway.enabled=false"})
@AutoConfigureMockMvc @Sql(scripts={"classpath:app-order-create-schema.sql","classpath:app-order-create-data.sql"})
class AppOrderCreateIntegrationTest {
 @Autowired MockMvc mvc; @Autowired JdbcTemplate jdbc; @Autowired AppOrderCreateService service;
 @Test void createsTravelOrderSnapshotsAndInitialLog() throws Exception {mvc.perform(post("/api/v1/app/orders").header("Idempotency-Key","travel-1").header("X-Request-Id","req-create").contentType("application/json").content(travelJson(101)))
  .andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("PENDING")).andExpect(jsonPath("$.data.carSpecSnapshot").value(org.hamcrest.Matchers.containsString("\"seatNum\":7"))).andExpect(jsonPath("$.data.contactPhone").value("138****8000"));
  assertThat(jdbc.queryForObject("select count(*) from reserve_order",Integer.class)).isEqualTo(1); assertThat(jdbc.queryForObject("select operator_type from order_status_log",String.class)).isEqualTo("USER"); assertThat(jdbc.queryForObject("select from_status from order_status_log",String.class)).isNull(); assertThat(jdbc.queryForObject("select request_id from order_status_log",String.class)).isEqualTo("req-create");}
 @Test void sameKeySamePayloadReturnsExistingAndDifferentPayloadConflicts() throws Exception {mvc.perform(post("/api/v1/app/orders").header("Idempotency-Key","same").contentType("application/json").content(travelJson(101))).andExpect(status().isOk());mvc.perform(post("/api/v1/app/orders").header("Idempotency-Key","same").contentType("application/json").content(travelJson(101))).andExpect(status().isOk());assertThat(jdbc.queryForObject("select count(*) from reserve_order",Integer.class)).isEqualTo(1);mvc.perform(post("/api/v1/app/orders").header("Idempotency-Key","same").contentType("application/json").content(travelJson(102))).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("IDEMPOTENCY_CONFLICT"));}
 @Test void rejectsWrongResourceDisabledBusinessAndMixedFields() throws Exception {mvc.perform(post("/api/v1/app/orders").header("Idempotency-Key","wrong").contentType("application/json").content(travelJson(103))).andExpect(status().isBadRequest());mvc.perform(post("/api/v1/app/orders").header("Idempotency-Key","disabled").contentType("application/json").content(foodJson(40))).andExpect(status().isConflict());mvc.perform(post("/api/v1/app/orders").header("Idempotency-Key","mixed").contentType("application/json").content(travelJson(101).replace("}",",\"mealPeriod\":\"LUNCH\"}"))).andExpect(status().isBadRequest());assertThat(jdbc.queryForObject("select count(*) from reserve_order",Integer.class)).isZero();}
 @Test void requiresIdempotencyKey() throws Exception {mvc.perform(post("/api/v1/app/orders").contentType("application/json").content(foodJson(30))).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value("VALIDATION_ERROR"));}
 @Test void concurrentSameRequestCreatesExactlyOneOrder() throws Exception {AppOrderCreateRequest r=travel();ExecutorService p=Executors.newFixedThreadPool(2);CountDownLatch ready=new CountDownLatch(2),start=new CountDownLatch(1);List<Future<Long>> fs=new ArrayList<Future<Long>>();for(int i=0;i<2;i++)fs.add(p.submit(()->{ready.countDown();start.await();return service.create("concurrent",r).getId();}));ready.await();start.countDown();assertThat(fs.get(0).get()).isEqualTo(fs.get(1).get());p.shutdownNow();assertThat(jdbc.queryForObject("select count(*) from reserve_order",Integer.class)).isEqualTo(1);}
 private AppOrderCreateRequest travel(){AppOrderCreateRequest r=new AppOrderCreateRequest();r.setOpenid("openid-a");r.setContactName("张三");r.setContactPhone("13800008000");r.setPeopleNum(2);r.setServiceDate(LocalDate.now().plusDays(1));r.setBusinessId(10L);r.setServiceType(BusinessType.TRAVEL);r.setCarId(101L);r.setCarQuantity(1);r.setServiceMode(ServiceMode.DAY_CHARTER);return r;}
 private String travelJson(long car){return "{\"openid\":\"openid-a\",\"contactName\":\"张三\",\"contactPhone\":\"13800008000\",\"peopleNum\":2,\"serviceDate\":\""+LocalDate.now().plusDays(1)+"\",\"businessId\":10,\"serviceType\":\"TRAVEL\",\"carId\":"+car+",\"carQuantity\":1,\"serviceMode\":\"DAY_CHARTER\"}";}
 private String foodJson(long business){return "{\"openid\":\"openid-b\",\"contactName\":\"李四\",\"contactPhone\":\"13900008000\",\"peopleNum\":2,\"serviceDate\":\""+LocalDate.now().plusDays(1)+"\",\"businessId\":"+business+",\"serviceType\":\"FOOD\",\"mealPeriod\":\"LUNCH\"}";}
}
