package com.mapvendor.module.business;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.mapvendor.MapVendorApplication; import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.context.jdbc.Sql; import org.springframework.test.web.servlet.MockMvc;
@SpringBootTest(classes=MapVendorApplication.class,properties={"spring.datasource.url=jdbc:h2:mem:resources;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1","spring.datasource.username=sa","spring.datasource.password=","spring.flyway.enabled=false"}) @AutoConfigureMockMvc @Sql(scripts={"classpath:business-resource-schema.sql","classpath:business-resource-data.sql"})
class AdminBusinessResourceIntegrationTest { @Autowired MockMvc mvc; @Autowired JdbcTemplate jdbc;
 @Test void supportsCrudStatusPaginationAndLogicalDelete() throws Exception {String car="{\"model\":\" Coach \" ,\"seatNum\":30}";mvc.perform(post("/api/v1/admin/businesses/10/cars").contentType(MediaType.APPLICATION_JSON).content(car)).andExpect(status().isOk()).andExpect(jsonPath("$.data.name").value("Coach"));mvc.perform(get("/api/v1/admin/businesses/10/cars").param("pageSize","1")).andExpect(status().isOk()).andExpect(jsonPath("$.data.total").value(2));mvc.perform(get("/api/v1/admin/businesses/10/cars/101")).andExpect(status().isOk()).andExpect(jsonPath("$.data.imageUrl").value("/api/v1/files/demo-car.jpg"));mvc.perform(patch("/api/v1/admin/businesses/10/cars/101/status").contentType(MediaType.APPLICATION_JSON).content("{\"status\":\"DISABLED\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("DISABLED"));mvc.perform(delete("/api/v1/admin/businesses/10/cars/101")).andExpect(status().isOk());mvc.perform(get("/api/v1/admin/businesses/10/cars/101")).andExpect(status().isNotFound());org.assertj.core.api.Assertions.assertThat(jdbc.queryForObject("SELECT deleted_at IS NOT NULL FROM business_travel_car WHERE id=101",Boolean.class)).isTrue();}
 @Test void listsImageResourceIdAndUrlForCarsRoomsAndDishes() throws Exception {mvc.perform(get("/api/v1/admin/businesses/10/cars").param("page","1").param("pageSize","100")).andExpect(status().isOk()).andExpect(jsonPath("$.data.items[0].imageResourceId").value(1)).andExpect(jsonPath("$.data.items[0].imageUrl").value("/api/v1/files/demo-car.jpg"));mvc.perform(get("/api/v1/admin/businesses/20/rooms")).andExpect(status().isOk()).andExpect(jsonPath("$.data.items[0].imageResourceId").value(2)).andExpect(jsonPath("$.data.items[0].imageUrl").value("/api/v1/files/demo-room.jpg"));mvc.perform(get("/api/v1/admin/businesses/30/dishes")).andExpect(status().isOk()).andExpect(jsonPath("$.data.items[0].imageResourceId").value(3)).andExpect(jsonPath("$.data.items[0].imageUrl").value("/api/v1/files/demo-dish.jpg"));}
 @Test void returnsImagesAfterCreateAndUpdateForEditorEcho() throws Exception {mvc.perform(post("/api/v1/admin/businesses/20/rooms").contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Twin\",\"bedSpec\":\"2 beds\",\"imageResourceId\":2}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.imageResourceId").value(2)).andExpect(jsonPath("$.data.imageUrl").value("/api/v1/files/demo-room.jpg"));mvc.perform(put("/api/v1/admin/businesses/30/dishes/301").contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Rice\",\"sortNo\":0,\"recommended\":false,\"imageResourceId\":3}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.imageResourceId").value(3)).andExpect(jsonPath("$.data.imageUrl").value("/api/v1/files/demo-dish.jpg"));}
 @Test void supportsRoomAndDishAndRejectsWrongTypeOrOwner() throws Exception {mvc.perform(post("/api/v1/admin/businesses/20/rooms").contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Twin\",\"bedSpec\":\"100×200cm×2张\"}")).andExpect(status().isOk());mvc.perform(post("/api/v1/admin/businesses/30/dishes").contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Rice\",\"sortNo\":0,\"recommended\":true}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.recommended").value(true));mvc.perform(get("/api/v1/admin/businesses/20/cars")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value("BUSINESS_TYPE_MISMATCH"));mvc.perform(get("/api/v1/admin/businesses/10/cars/102")).andExpect(status().isNotFound()).andExpect(jsonPath("$.code").value("RESOURCE_NOT_FOUND"));}
 @Test void validatesPositiveNumbersAndPublishesRoutes() throws Exception {mvc.perform(post("/api/v1/admin/businesses/10/cars").contentType(MediaType.APPLICATION_JSON).content("{\"model\":\"x\",\"seatNum\":0}")).andExpect(status().isBadRequest());mvc.perform(get("/v3/api-docs/admin")).andExpect(status().isOk()).andExpect(jsonPath("$.paths['/api/v1/admin/businesses/{businessId}/cars'].post").exists()).andExpect(jsonPath("$.paths['/api/v1/admin/businesses/{businessId}/rooms/{id}'].delete").exists()).andExpect(jsonPath("$.paths['/api/v1/admin/businesses/{businessId}/dishes/{id}/status'].patch").exists());}
}
